### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by ell-bee** [ell-bee/drawings#1]
my sketch is really simple, so I don't see where I could create a variable to consolidate my code for the placement of each circle, but I could make a variable to store a color, but I feel like that's adding unnecessary code.
@mrjloswald-avenues

**Comment by mrjloswald-avenues** [comment]
I agree somewhat with your assessment here, but I think you definitely could have used a variable to store `x/3` and `y/5`. It isn't a huge performance gain, but it generally does make sense to do something like this.
